path_planner:
  ros__parameters:
    map_path: ""
    checkpoint_file: ""
    route_update_hz: 10.0
    frenet_planner_hz: 20.0
    max_path_length: 50.0
    lateral_cost_weight: 1.0
    time_cost_weight: 1.0
    goal_cost_weight: 10.0
    progress_cost_weight: 1.0
    alignment_cost_weight: 10.0
    checkpoint_radius_m: 2.0
    heading_tolerance_deg: 10.0
    alignment_duration_s: 3.0
    frenet_horizon_candidates_s: [2.0, 3.0, 4.0]
    xy_resolution_m: 0.5
    time_resolution_s: 0.5
    planning_accel_limit_mps2: 5.45
    planning_decel_limit_mps2: 10.37
    rear_axle_to_front_m: 3.808
    rear_axle_to_rear_m: 1.040
    left_extent_m: 0.943
    right_extent_m: 0.943
    vehicle_height_m: 1.507
