<?xml version="1.0"?>
<package format="3">
    <name>tf_broadcasting</name>
    <version>0.1.0</version>
    <description>tf_broadcasting for VTD</description>
    <maintainer email="ppong030206@gmail.com">stier</maintainer>
    <license>Proprietary</license>
    <buildtool_depend>ament_cmake</buildtool_depend>
    <depend>ament_cmake_python</depend>
    <depend>rclpy</depend>
    <depend>interfaces</depend>
    <depend>geometry_msgs</depend>
    <depend>tf2_ros_py</depend>
    <export><build_type>ament_cmake</build_type></export>
</package>
